user:
  kafka:
    store: resource-user-state-store

resource:
  kafka:
    server: localhost:9092
    topic: resource
    replicates: 1
    partitions: 1
    store: resource-state-store
    retention: -1
    acks: all
    retries: 10
    requestimeout: 5000
    batch: 163850
    linger: 100
    max-in-flight: 1
    client-id: apollo-resource
    group-id: apollo-resource-group
    offset: latest


spring:
  cloud:
    function:
      definition: resourceProcessorState;resourceUserProcessorState;
    stream:
      kafka:
        streams:
          binder:
            functions:
              resourceProcessorState:
                application-id: apollo-resource
              resourceUserProcessorState:
                application-id: apollo-resource-user
      bindings:
        resourceProcessorState-in-0.destination: ${resource.kafka.topic}
        resourceProcessorState-out-0.destination: ${resource.kafka.store}
        resourceUserProcessorState-in-0.destination: ${resource.kafka.topic}
        resourceUserProcessorState-out-0.destination: ${user.kafka.store}

server:
  port: 8084
